# -*- makefile -*-

CC=gcc
CCOPTS=-Wall -Wno-import -D_ROBOT_CLIENT -D_LINUX

OBJECTS=CornerRobot.o CornerRobot_main.o Vector.o

all : CornerRobot.linux

%.o : %.m
	$(CC) $(CCOPTS) -c $<

%.o : %.c
	$(CC) $(CCOPTS) -c $<

CornerRobot.linux : $(OBJECTS)
	$(CC) -o $@ $(OBJECTS) -L../RobotClient -lm -ldl -lRobotClient -lFoundation -lobjc

clean :
	-rm *~ *.o libRobotClient.a
